#! /bin/sh

bspc config border_width        2
bspc config window_gap          12
bspc config top_padding         14

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc monitor -d Main Web Work Term Misc

#! bspc rule -a Chromium desktop=^2

xsetroot -cursor_name left_ptr &
